name: Rust

on:
  pull_request:
    branches:
      - master
    paths:
      - src/*

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
